Update de.json
mspaint-cc/translations pull request #1
Opened 2024-11-26 00:08 UTC by ld2303

The Older Version was to dificould. i make it simple

2024-11-26 00:17 UTC, notpoiu commented
LGTM, but im gonna ask oogway for approval.

2024-11-26 00:22 UTC, ld2303 commented
Okay

On Tue 26. Nov 2024 at 01:18, upio ***@***.***> wrote:

> LGTM, but im gonna ask oogway for approval.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mspaint-cc/translations/pull/1#issuecomment-2499296405>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5LJJWQU7JUSQN5DKL4VRZL2CO44HAVCNFSM6AAAAABSPFR53SVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIOJZGI4TMNBQGU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-11-26 12:22 UTC, notpoiu commented
1. Just keep the word Rift no need to translate it to „Riss“
2. Spam andere Werkzeuge -> Andere Werkzeuge spammen
3. Umgekehrt -> Auf dem Kopf stehen
4. Just use Gold and Knobs instead of „Währung“ or „Knopf“

2024-11-26 13:04 UTC, notpoiu requested changes
Just keep the word Rift no need to translate it to „Riss“

Change Spam andere Werkzeuge to Andere Werkzeuge spammen

Change Umgekehrt to Auf dem Kopf stehen
 
Just use Gold and Knobs instead of „Währung“ or „Knopf“

2024-11-26 16:49 UTC, ld2303 commented
Okey

2024-11-29 19:14 UTC, deividcomsono commented
**those who know**

2024-11-29 19:16 UTC, notpoiu commented
those who dont know!!

2024-11-29 19:16 UTC, notpoiu commented
theres merge conflicts

2024-12-05 20:25 UTC, closed without merging